/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cbhb_hce_NativeUtil */

#ifndef _Included_com_cbhb_hce_NativeUtil
#define _Included_com_cbhb_hce_NativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cbhb_hce_NativeUtil
 * Method:    test
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_cbhb_hce_NativeUtil_test
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_cbhb_hce_NativeUtil
 * Method:    computeAccessPinHash
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cbhb_hce_NativeUtil_computeAccessPinHash
  (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     com_cbhb_hce_NativeUtil
 * Method:    verifyAccessPinHash
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_cbhb_hce_NativeUtil_verifyAccessPinHash
  (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     com_cbhb_hce_NativeUtil
 * Method:    init
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_cbhb_hce_NativeUtil_init
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_cbhb_hce_NativeUtil
 * Method:    getToken
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cbhb_hce_NativeUtil_getToken
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_cbhb_hce_NativeUtil
 * Method:    setHostSalt
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cbhb_hce_NativeUtil_setHostSalt
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_cbhb_hce_NativeUtil
 * Method:    getHostSalt
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cbhb_hce_NativeUtil_getHostSalt
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_cbhb_hce_NativeUtil
 * Method:    setHostGroupId
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cbhb_hce_NativeUtil_setHostGroupId
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_cbhb_hce_NativeUtil
 * Method:    getHostGroupId
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cbhb_hce_NativeUtil_getHostGroupId
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_cbhb_hce_NativeUtil
 * Method:    setHostDek
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cbhb_hce_NativeUtil_setHostDek
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_cbhb_hce_NativeUtil
 * Method:    setHostPpseResp
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cbhb_hce_NativeUtil_setHostPpseResp
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_cbhb_hce_NativeUtil
 * Method:    setHostAidResp
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cbhb_hce_NativeUtil_setHostAidResp
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_cbhb_hce_NativeUtil
 * Method:    setHostCardInfo
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cbhb_hce_NativeUtil_setHostCardInfo
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_cbhb_hce_NativeUtil
 * Method:    setHostPayment
 * Signature: (Ljava/lang/Object;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cbhb_hce_NativeUtil_setHostPayment
  (JNIEnv *, jclass, jobject, jint, jstring);

/*
 * Class:     com_cbhb_hce_NativeUtil
 * Method:    setAccessPinHash
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cbhb_hce_NativeUtil_setAccessPinHash
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_cbhb_hce_NativeUtil
 * Method:    checkup
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_cbhb_hce_NativeUtil_checkup
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_cbhb_hce_NativeUtil
 * Method:    getGpoResponse
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cbhb_hce_NativeUtil_getGpoResponse
  (JNIEnv *, jclass, jobject, jstring, jstring, jstring);

/*
 * Class:     com_cbhb_hce_NativeUtil
 * Method:    getSelectPpseResp
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cbhb_hce_NativeUtil_getSelectPpseResp
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_cbhb_hce_NativeUtil
 * Method:    getSelectAidResp
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cbhb_hce_NativeUtil_getSelectAidResp
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_cbhb_hce_NativeUtil
 * Method:    removePayment
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_cbhb_hce_NativeUtil_removePayment
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_cbhb_hce_NativeUtil
 * Method:    removeCard
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_cbhb_hce_NativeUtil_removeCard
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_cbhb_hce_NativeUtil
 * Method:    getDeviceId
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cbhb_hce_NativeUtil_getDeviceId
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_cbhb_hce_NativeUtil
 * Method:    getPaymentCount
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_cbhb_hce_NativeUtil_getPaymentCount
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
